server:
  port: 7002


eureka:
  instance:
    hostname: eureka7002.com  #eureka服务端的实例名称
  client:
    register-with-eureka: false  #注册中心  不注册自己
    fetch-registry: false  #false表示自己端就是注册中心，我的职责就是维护服务服务实例，不需要去检索服务
    service-url:
      #设置与Eurekaserver 交互的地址查询服务和注册服务都需要这个地址
      defaultZone:  http://eureka7001.com:7001/eureka/   #相互守望 守望相助
  server:
    enable-self-preservation: false  # 警用eureka 自我保护模式