server:
  port: 8401
spring:
  application:
    name: cloudALibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        secret-key: localhost:8848  #配置nacos地址
    sentinel:
      transport:
        dashboard: localhost:8080  #配置sentinel dashboard的地址
        port: 8719 #默认8719端口，假如被占用会自动从8719开始依次—+1扫描，直至找到为占用的端口
        datasource:
          ds1:
            nacos:
              server-addr: localhost:8848
              dataId: ${spring.application.name}
              groupId: DEFAULT_GROUP
              data-type: json
              rule-type: flow

management:
  endpoints:
    web:
      exposure:
        exclude: "*"
