server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        secret-key: localhost:8848  #配置nacos地址
    sentinel:
      transport:
        dashboard: localhost:8080  #配置sentinel dashboard的地址
        port: 8719 #默认8719端口，假如被占用会自动从8719开始依次—+1扫描，直至找到为占用的端口

management:
  endpoints:
    web:
      exposure:
        exclude: "*"

#消费者将要访问的微服务名称（注册成功进nacos的微服务框架）
service-url:
  nacos-user-service: http://nacos-payment-provider

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true
