server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样率介于0到1,1表示全部采集
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.jiatp.springcloud.entity #支持别名 所在包

  #eureka配置
eureka:
  client:
    register-with-eureka: true  #向eureka server 注册自己
    fetch-registry: true  #s是否从eureka server 抓取已有信息，默认为true 单节点无所谓，集群条件必须设置为true,才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/   #集群版
  instance:
    instance-id: payment8001
    prefer-ip-address: true  # 访问路径有IP提示
    #eureka客户端向服务端发送心跳的时间间隔 ，单位为秒 ，默认30
    lease-renewal-interval-in-seconds: 1
    #eureka服务端在收到最后一次心跳后等待的时间上限。单位为秒，默认90s
    lease-expiration-duration-in-seconds: 2

  server:
    enable-self-preservation: false  # 警用eureka 自我保护模式
