server:
  port: 8802

  #eureka配置
eureka:
  client:
    register-with-eureka: true  #向eureka server 注册自己
    fetch-registry: true  #s是否从eureka server 抓取已有信息，默认为true 单节点无所谓，集群条件必须设置为true,才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/   #集群版
  instance:
    instance-id: send-8802.com
    prefer-ip-address: true  # 访问路径有IP提示
    #eureka客户端向服务端发送心跳的时间间隔 ，单位为秒 ，默认30
    lease-renewal-interval-in-seconds: 1
    #eureka服务端在收到最后一次心跳后等待的时间上限。单位为秒，默认90s
    lease-expiration-duration-in-seconds: 2
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:  #此处要绑定的消息服务
        defaultRabbit: #表示定义的名称，用于binding命令
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:  #服务的整合处理
        input:   #个名字是通道的名称
          destination: studyExchange #表示要使用的Exchange名称
          content-type: application/json  #设置消息类型，本次为json
          binder: defaultRabbit #设置要绑定的消息服务的具体类型
          #group: jiatp
