server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务进行路由
      routes:
        - id: payment_routh                      #路由的id,没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service
        #  uri: http://localhost:8001             #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**               # 断言，路径相匹配进行路由
        - id: payment_routh2
        #  uri: http://localhost:8001
          uri: lb://cloud-payment-service        #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**
           # - After=2020-04-01T21:06:06.793+08:00[Asia/Shanghai]
           # - Cookie=username,jiatp
           # - Header=X-Request-Id, \d+        #请求头要有X-Request_Id属性且值为整数的正则表达式



  #eureka配置
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true  #向eureka server 注册自己
    fetch-registry: true  #s是否从eureka server 抓取已有信息，默认为true 单节点无所谓，集群条件必须设置为true,才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/   #集群版