server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        secret-key: localhost:8848  #配置nacos地址

management:
  endpoints:
    web:
      exposure:
        exclude: "*"
