server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        secret-key: localhost:8848  #配置nacos地址

management:
  endpoints:
    web:
      exposure:
        exclude: "*"

#消费者将要访问的微服务名称（注册成功进nacos的微服务框架）
service-url:
  nacos-user-service: http://nacos-payment-provider