server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment
    #zookeeper地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: 123456

  cloud:
    zookeeper:
      connect-string: 192.168.234.130:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.jiatp.springcloud.entity #支持别名 所在包

