server:
  port: 80

  #eureka配置
eureka:
  client:
    register-with-eureka: true  #向eureka server 注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/   #集群版

  #feign客户端默认支持ribbon
ribbon:
  ReadTimeout: 5000
  ConnectTimeOut: 5000
feign:
  hystrix:
    enabled: true
